//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrivateTraining.Shaparak {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interfaces.core.sw.bps.com/", ConfigurationName="Shaparak.IPaymentGateway")]
    public interface IPaymentGateway {
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PrivateTraining.Shaparak.bpVerifyRequestResponse bpVerifyRequest(PrivateTraining.Shaparak.bpVerifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpVerifyRequestResponse> bpVerifyRequestAsync(PrivateTraining.Shaparak.bpVerifyRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PrivateTraining.Shaparak.bpRefundInquiryRequestResponse bpRefundInquiryRequest(PrivateTraining.Shaparak.bpRefundInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpRefundInquiryRequestResponse> bpRefundInquiryRequestAsync(PrivateTraining.Shaparak.bpRefundInquiryRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PrivateTraining.Shaparak.bpRefundVerifyRequestResponse bpRefundVerifyRequest(PrivateTraining.Shaparak.bpRefundVerifyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpRefundVerifyRequestResponse> bpRefundVerifyRequestAsync(PrivateTraining.Shaparak.bpRefundVerifyRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PrivateTraining.Shaparak.bpSettleRequestResponse bpSettleRequest(PrivateTraining.Shaparak.bpSettleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpSettleRequestResponse> bpSettleRequestAsync(PrivateTraining.Shaparak.bpSettleRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PrivateTraining.Shaparak.bpDynamicPayRequestResponse bpDynamicPayRequest(PrivateTraining.Shaparak.bpDynamicPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpDynamicPayRequestResponse> bpDynamicPayRequestAsync(PrivateTraining.Shaparak.bpDynamicPayRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PrivateTraining.Shaparak.bpVirtualPayRequestResponse bpVirtualPayRequest(PrivateTraining.Shaparak.bpVirtualPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpVirtualPayRequestResponse> bpVirtualPayRequestAsync(PrivateTraining.Shaparak.bpVirtualPayRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PrivateTraining.Shaparak.bpReversalRequestResponse bpReversalRequest(PrivateTraining.Shaparak.bpReversalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpReversalRequestResponse> bpReversalRequestAsync(PrivateTraining.Shaparak.bpReversalRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PrivateTraining.Shaparak.bpCumulativeDynamicPayRequestResponse bpCumulativeDynamicPayRequest(PrivateTraining.Shaparak.bpCumulativeDynamicPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpCumulativeDynamicPayRequestResponse> bpCumulativeDynamicPayRequestAsync(PrivateTraining.Shaparak.bpCumulativeDynamicPayRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PrivateTraining.Shaparak.bpPayRequestResponse bpPayRequest(PrivateTraining.Shaparak.bpPayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpPayRequestResponse> bpPayRequestAsync(PrivateTraining.Shaparak.bpPayRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PrivateTraining.Shaparak.bpSaleReferenceIdRequestResponse bpSaleReferenceIdRequest(PrivateTraining.Shaparak.bpSaleReferenceIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpSaleReferenceIdRequestResponse> bpSaleReferenceIdRequestAsync(PrivateTraining.Shaparak.bpSaleReferenceIdRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PrivateTraining.Shaparak.bpChargePayRequestResponse bpChargePayRequest(PrivateTraining.Shaparak.bpChargePayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpChargePayRequestResponse> bpChargePayRequestAsync(PrivateTraining.Shaparak.bpChargePayRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PrivateTraining.Shaparak.bpInquiryRequestResponse bpInquiryRequest(PrivateTraining.Shaparak.bpInquiryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpInquiryRequestResponse> bpInquiryRequestAsync(PrivateTraining.Shaparak.bpInquiryRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        PrivateTraining.Shaparak.bpRefundRequestResponse bpRefundRequest(PrivateTraining.Shaparak.bpRefundRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpRefundRequestResponse> bpRefundRequestAsync(PrivateTraining.Shaparak.bpRefundRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpVerifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpVerifyRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpVerifyRequestBody Body;
        
        public bpVerifyRequest() {
        }
        
        public bpVerifyRequest(PrivateTraining.Shaparak.bpVerifyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpVerifyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpVerifyRequestBody() {
        }
        
        public bpVerifyRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpVerifyRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpVerifyRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpVerifyRequestResponseBody Body;
        
        public bpVerifyRequestResponse() {
        }
        
        public bpVerifyRequestResponse(PrivateTraining.Shaparak.bpVerifyRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpVerifyRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpVerifyRequestResponseBody() {
        }
        
        public bpVerifyRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundInquiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundInquiryRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpRefundInquiryRequestBody Body;
        
        public bpRefundInquiryRequest() {
        }
        
        public bpRefundInquiryRequest(PrivateTraining.Shaparak.bpRefundInquiryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundInquiryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long refundOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long refundReferenceId;
        
        public bpRefundInquiryRequestBody() {
        }
        
        public bpRefundInquiryRequestBody(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.refundOrderId = refundOrderId;
            this.refundReferenceId = refundReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundInquiryRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundInquiryRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpRefundInquiryRequestResponseBody Body;
        
        public bpRefundInquiryRequestResponse() {
        }
        
        public bpRefundInquiryRequestResponse(PrivateTraining.Shaparak.bpRefundInquiryRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundInquiryRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpRefundInquiryRequestResponseBody() {
        }
        
        public bpRefundInquiryRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundVerifyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundVerifyRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpRefundVerifyRequestBody Body;
        
        public bpRefundVerifyRequest() {
        }
        
        public bpRefundVerifyRequest(PrivateTraining.Shaparak.bpRefundVerifyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundVerifyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long refundOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long refundReferenceId;
        
        public bpRefundVerifyRequestBody() {
        }
        
        public bpRefundVerifyRequestBody(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.refundOrderId = refundOrderId;
            this.refundReferenceId = refundReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundVerifyRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundVerifyRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpRefundVerifyRequestResponseBody Body;
        
        public bpRefundVerifyRequestResponse() {
        }
        
        public bpRefundVerifyRequestResponse(PrivateTraining.Shaparak.bpRefundVerifyRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundVerifyRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpRefundVerifyRequestResponseBody() {
        }
        
        public bpRefundVerifyRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpSettleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSettleRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpSettleRequestBody Body;
        
        public bpSettleRequest() {
        }
        
        public bpSettleRequest(PrivateTraining.Shaparak.bpSettleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpSettleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpSettleRequestBody() {
        }
        
        public bpSettleRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpSettleRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSettleRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpSettleRequestResponseBody Body;
        
        public bpSettleRequestResponse() {
        }
        
        public bpSettleRequestResponse(PrivateTraining.Shaparak.bpSettleRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpSettleRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpSettleRequestResponseBody() {
        }
        
        public bpSettleRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpDynamicPayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpDynamicPayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpDynamicPayRequestBody Body;
        
        public bpDynamicPayRequest() {
        }
        
        public bpDynamicPayRequest(PrivateTraining.Shaparak.bpDynamicPayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpDynamicPayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public long payerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public long subServiceId;
        
        public bpDynamicPayRequestBody() {
        }
        
        public bpDynamicPayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId, long subServiceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
            this.payerId = payerId;
            this.subServiceId = subServiceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpDynamicPayRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpDynamicPayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpDynamicPayRequestResponseBody Body;
        
        public bpDynamicPayRequestResponse() {
        }
        
        public bpDynamicPayRequestResponse(PrivateTraining.Shaparak.bpDynamicPayRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpDynamicPayRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpDynamicPayRequestResponseBody() {
        }
        
        public bpDynamicPayRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpVirtualPayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpVirtualPayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpVirtualPayRequestBody Body;
        
        public bpVirtualPayRequest() {
        }
        
        public bpVirtualPayRequest(PrivateTraining.Shaparak.bpVirtualPayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpVirtualPayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public long payerId;
        
        public bpVirtualPayRequestBody() {
        }
        
        public bpVirtualPayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
            this.payerId = payerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpVirtualPayRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpVirtualPayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpVirtualPayRequestResponseBody Body;
        
        public bpVirtualPayRequestResponse() {
        }
        
        public bpVirtualPayRequestResponse(PrivateTraining.Shaparak.bpVirtualPayRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpVirtualPayRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpVirtualPayRequestResponseBody() {
        }
        
        public bpVirtualPayRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpReversalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpReversalRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpReversalRequestBody Body;
        
        public bpReversalRequest() {
        }
        
        public bpReversalRequest(PrivateTraining.Shaparak.bpReversalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpReversalRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpReversalRequestBody() {
        }
        
        public bpReversalRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpReversalRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpReversalRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpReversalRequestResponseBody Body;
        
        public bpReversalRequestResponse() {
        }
        
        public bpReversalRequestResponse(PrivateTraining.Shaparak.bpReversalRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpReversalRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpReversalRequestResponseBody() {
        }
        
        public bpReversalRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpCumulativeDynamicPayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpCumulativeDynamicPayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpCumulativeDynamicPayRequestBody Body;
        
        public bpCumulativeDynamicPayRequest() {
        }
        
        public bpCumulativeDynamicPayRequest(PrivateTraining.Shaparak.bpCumulativeDynamicPayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpCumulativeDynamicPayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        public bpCumulativeDynamicPayRequestBody() {
        }
        
        public bpCumulativeDynamicPayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpCumulativeDynamicPayRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpCumulativeDynamicPayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpCumulativeDynamicPayRequestResponseBody Body;
        
        public bpCumulativeDynamicPayRequestResponse() {
        }
        
        public bpCumulativeDynamicPayRequestResponse(PrivateTraining.Shaparak.bpCumulativeDynamicPayRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpCumulativeDynamicPayRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpCumulativeDynamicPayRequestResponseBody() {
        }
        
        public bpCumulativeDynamicPayRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpPayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpPayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpPayRequestBody Body;
        
        public bpPayRequest() {
        }
        
        public bpPayRequest(PrivateTraining.Shaparak.bpPayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpPayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public long payerId;
        
        public bpPayRequestBody() {
        }
        
        public bpPayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
            this.payerId = payerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpPayRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpPayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpPayRequestResponseBody Body;
        
        public bpPayRequestResponse() {
        }
        
        public bpPayRequestResponse(PrivateTraining.Shaparak.bpPayRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpPayRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpPayRequestResponseBody() {
        }
        
        public bpPayRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpSaleReferenceIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSaleReferenceIdRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpSaleReferenceIdRequestBody Body;
        
        public bpSaleReferenceIdRequest() {
        }
        
        public bpSaleReferenceIdRequest(PrivateTraining.Shaparak.bpSaleReferenceIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpSaleReferenceIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        public bpSaleReferenceIdRequestBody() {
        }
        
        public bpSaleReferenceIdRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpSaleReferenceIdRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpSaleReferenceIdRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpSaleReferenceIdRequestResponseBody Body;
        
        public bpSaleReferenceIdRequestResponse() {
        }
        
        public bpSaleReferenceIdRequestResponse(PrivateTraining.Shaparak.bpSaleReferenceIdRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpSaleReferenceIdRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpSaleReferenceIdRequestResponseBody() {
        }
        
        public bpSaleReferenceIdRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpChargePayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpChargePayRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpChargePayRequestBody Body;
        
        public bpChargePayRequest() {
        }
        
        public bpChargePayRequest(PrivateTraining.Shaparak.bpChargePayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpChargePayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string localDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string additionalData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string callBackUrl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public long payerId;
        
        public bpChargePayRequestBody() {
        }
        
        public bpChargePayRequestBody(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.amount = amount;
            this.localDate = localDate;
            this.localTime = localTime;
            this.additionalData = additionalData;
            this.callBackUrl = callBackUrl;
            this.payerId = payerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpChargePayRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpChargePayRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpChargePayRequestResponseBody Body;
        
        public bpChargePayRequestResponse() {
        }
        
        public bpChargePayRequestResponse(PrivateTraining.Shaparak.bpChargePayRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpChargePayRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpChargePayRequestResponseBody() {
        }
        
        public bpChargePayRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpInquiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpInquiryRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpInquiryRequestBody Body;
        
        public bpInquiryRequest() {
        }
        
        public bpInquiryRequest(PrivateTraining.Shaparak.bpInquiryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpInquiryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        public bpInquiryRequestBody() {
        }
        
        public bpInquiryRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpInquiryRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpInquiryRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpInquiryRequestResponseBody Body;
        
        public bpInquiryRequestResponse() {
        }
        
        public bpInquiryRequestResponse(PrivateTraining.Shaparak.bpInquiryRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpInquiryRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpInquiryRequestResponseBody() {
        }
        
        public bpInquiryRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundRequest", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpRefundRequestBody Body;
        
        public bpRefundRequest() {
        }
        
        public bpRefundRequest(PrivateTraining.Shaparak.bpRefundRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long terminalId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long orderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long saleOrderId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public long saleReferenceId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public long refundAmount;
        
        public bpRefundRequestBody() {
        }
        
        public bpRefundRequestBody(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId, long refundAmount) {
            this.terminalId = terminalId;
            this.userName = userName;
            this.userPassword = userPassword;
            this.orderId = orderId;
            this.saleOrderId = saleOrderId;
            this.saleReferenceId = saleReferenceId;
            this.refundAmount = refundAmount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bpRefundRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bpRefundRequestResponse", Namespace="http://interfaces.core.sw.bps.com/", Order=0)]
        public PrivateTraining.Shaparak.bpRefundRequestResponseBody Body;
        
        public bpRefundRequestResponse() {
        }
        
        public bpRefundRequestResponse(PrivateTraining.Shaparak.bpRefundRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class bpRefundRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public bpRefundRequestResponseBody() {
        }
        
        public bpRefundRequestResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentGatewayChannel : PrivateTraining.Shaparak.IPaymentGateway, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentGatewayClient : System.ServiceModel.ClientBase<PrivateTraining.Shaparak.IPaymentGateway>, PrivateTraining.Shaparak.IPaymentGateway {
        
        public PaymentGatewayClient() {
        }
        
        public PaymentGatewayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentGatewayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentGatewayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentGatewayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateTraining.Shaparak.bpVerifyRequestResponse PrivateTraining.Shaparak.IPaymentGateway.bpVerifyRequest(PrivateTraining.Shaparak.bpVerifyRequest request) {
            return base.Channel.bpVerifyRequest(request);
        }
        
        public string bpVerifyRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            PrivateTraining.Shaparak.bpVerifyRequest inValue = new PrivateTraining.Shaparak.bpVerifyRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpVerifyRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            PrivateTraining.Shaparak.bpVerifyRequestResponse retVal = ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpVerifyRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpVerifyRequestResponse> PrivateTraining.Shaparak.IPaymentGateway.bpVerifyRequestAsync(PrivateTraining.Shaparak.bpVerifyRequest request) {
            return base.Channel.bpVerifyRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpVerifyRequestResponse> bpVerifyRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            PrivateTraining.Shaparak.bpVerifyRequest inValue = new PrivateTraining.Shaparak.bpVerifyRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpVerifyRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            return ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpVerifyRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateTraining.Shaparak.bpRefundInquiryRequestResponse PrivateTraining.Shaparak.IPaymentGateway.bpRefundInquiryRequest(PrivateTraining.Shaparak.bpRefundInquiryRequest request) {
            return base.Channel.bpRefundInquiryRequest(request);
        }
        
        public string bpRefundInquiryRequest(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            PrivateTraining.Shaparak.bpRefundInquiryRequest inValue = new PrivateTraining.Shaparak.bpRefundInquiryRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpRefundInquiryRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.refundOrderId = refundOrderId;
            inValue.Body.refundReferenceId = refundReferenceId;
            PrivateTraining.Shaparak.bpRefundInquiryRequestResponse retVal = ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpRefundInquiryRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpRefundInquiryRequestResponse> PrivateTraining.Shaparak.IPaymentGateway.bpRefundInquiryRequestAsync(PrivateTraining.Shaparak.bpRefundInquiryRequest request) {
            return base.Channel.bpRefundInquiryRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpRefundInquiryRequestResponse> bpRefundInquiryRequestAsync(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            PrivateTraining.Shaparak.bpRefundInquiryRequest inValue = new PrivateTraining.Shaparak.bpRefundInquiryRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpRefundInquiryRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.refundOrderId = refundOrderId;
            inValue.Body.refundReferenceId = refundReferenceId;
            return ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpRefundInquiryRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateTraining.Shaparak.bpRefundVerifyRequestResponse PrivateTraining.Shaparak.IPaymentGateway.bpRefundVerifyRequest(PrivateTraining.Shaparak.bpRefundVerifyRequest request) {
            return base.Channel.bpRefundVerifyRequest(request);
        }
        
        public string bpRefundVerifyRequest(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            PrivateTraining.Shaparak.bpRefundVerifyRequest inValue = new PrivateTraining.Shaparak.bpRefundVerifyRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpRefundVerifyRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.refundOrderId = refundOrderId;
            inValue.Body.refundReferenceId = refundReferenceId;
            PrivateTraining.Shaparak.bpRefundVerifyRequestResponse retVal = ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpRefundVerifyRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpRefundVerifyRequestResponse> PrivateTraining.Shaparak.IPaymentGateway.bpRefundVerifyRequestAsync(PrivateTraining.Shaparak.bpRefundVerifyRequest request) {
            return base.Channel.bpRefundVerifyRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpRefundVerifyRequestResponse> bpRefundVerifyRequestAsync(long terminalId, string userName, string userPassword, long orderId, long refundOrderId, long refundReferenceId) {
            PrivateTraining.Shaparak.bpRefundVerifyRequest inValue = new PrivateTraining.Shaparak.bpRefundVerifyRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpRefundVerifyRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.refundOrderId = refundOrderId;
            inValue.Body.refundReferenceId = refundReferenceId;
            return ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpRefundVerifyRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateTraining.Shaparak.bpSettleRequestResponse PrivateTraining.Shaparak.IPaymentGateway.bpSettleRequest(PrivateTraining.Shaparak.bpSettleRequest request) {
            return base.Channel.bpSettleRequest(request);
        }
        
        public string bpSettleRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            PrivateTraining.Shaparak.bpSettleRequest inValue = new PrivateTraining.Shaparak.bpSettleRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpSettleRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            PrivateTraining.Shaparak.bpSettleRequestResponse retVal = ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpSettleRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpSettleRequestResponse> PrivateTraining.Shaparak.IPaymentGateway.bpSettleRequestAsync(PrivateTraining.Shaparak.bpSettleRequest request) {
            return base.Channel.bpSettleRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpSettleRequestResponse> bpSettleRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            PrivateTraining.Shaparak.bpSettleRequest inValue = new PrivateTraining.Shaparak.bpSettleRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpSettleRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            return ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpSettleRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateTraining.Shaparak.bpDynamicPayRequestResponse PrivateTraining.Shaparak.IPaymentGateway.bpDynamicPayRequest(PrivateTraining.Shaparak.bpDynamicPayRequest request) {
            return base.Channel.bpDynamicPayRequest(request);
        }
        
        public string bpDynamicPayRequest(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId, long subServiceId) {
            PrivateTraining.Shaparak.bpDynamicPayRequest inValue = new PrivateTraining.Shaparak.bpDynamicPayRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpDynamicPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            inValue.Body.subServiceId = subServiceId;
            PrivateTraining.Shaparak.bpDynamicPayRequestResponse retVal = ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpDynamicPayRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpDynamicPayRequestResponse> PrivateTraining.Shaparak.IPaymentGateway.bpDynamicPayRequestAsync(PrivateTraining.Shaparak.bpDynamicPayRequest request) {
            return base.Channel.bpDynamicPayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpDynamicPayRequestResponse> bpDynamicPayRequestAsync(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId, long subServiceId) {
            PrivateTraining.Shaparak.bpDynamicPayRequest inValue = new PrivateTraining.Shaparak.bpDynamicPayRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpDynamicPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            inValue.Body.subServiceId = subServiceId;
            return ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpDynamicPayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateTraining.Shaparak.bpVirtualPayRequestResponse PrivateTraining.Shaparak.IPaymentGateway.bpVirtualPayRequest(PrivateTraining.Shaparak.bpVirtualPayRequest request) {
            return base.Channel.bpVirtualPayRequest(request);
        }
        
        public string bpVirtualPayRequest(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            PrivateTraining.Shaparak.bpVirtualPayRequest inValue = new PrivateTraining.Shaparak.bpVirtualPayRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpVirtualPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            PrivateTraining.Shaparak.bpVirtualPayRequestResponse retVal = ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpVirtualPayRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpVirtualPayRequestResponse> PrivateTraining.Shaparak.IPaymentGateway.bpVirtualPayRequestAsync(PrivateTraining.Shaparak.bpVirtualPayRequest request) {
            return base.Channel.bpVirtualPayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpVirtualPayRequestResponse> bpVirtualPayRequestAsync(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            PrivateTraining.Shaparak.bpVirtualPayRequest inValue = new PrivateTraining.Shaparak.bpVirtualPayRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpVirtualPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            return ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpVirtualPayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateTraining.Shaparak.bpReversalRequestResponse PrivateTraining.Shaparak.IPaymentGateway.bpReversalRequest(PrivateTraining.Shaparak.bpReversalRequest request) {
            return base.Channel.bpReversalRequest(request);
        }
        
        public string bpReversalRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            PrivateTraining.Shaparak.bpReversalRequest inValue = new PrivateTraining.Shaparak.bpReversalRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpReversalRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            PrivateTraining.Shaparak.bpReversalRequestResponse retVal = ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpReversalRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpReversalRequestResponse> PrivateTraining.Shaparak.IPaymentGateway.bpReversalRequestAsync(PrivateTraining.Shaparak.bpReversalRequest request) {
            return base.Channel.bpReversalRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpReversalRequestResponse> bpReversalRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            PrivateTraining.Shaparak.bpReversalRequest inValue = new PrivateTraining.Shaparak.bpReversalRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpReversalRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            return ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpReversalRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateTraining.Shaparak.bpCumulativeDynamicPayRequestResponse PrivateTraining.Shaparak.IPaymentGateway.bpCumulativeDynamicPayRequest(PrivateTraining.Shaparak.bpCumulativeDynamicPayRequest request) {
            return base.Channel.bpCumulativeDynamicPayRequest(request);
        }
        
        public string bpCumulativeDynamicPayRequest(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl) {
            PrivateTraining.Shaparak.bpCumulativeDynamicPayRequest inValue = new PrivateTraining.Shaparak.bpCumulativeDynamicPayRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpCumulativeDynamicPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            PrivateTraining.Shaparak.bpCumulativeDynamicPayRequestResponse retVal = ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpCumulativeDynamicPayRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpCumulativeDynamicPayRequestResponse> PrivateTraining.Shaparak.IPaymentGateway.bpCumulativeDynamicPayRequestAsync(PrivateTraining.Shaparak.bpCumulativeDynamicPayRequest request) {
            return base.Channel.bpCumulativeDynamicPayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpCumulativeDynamicPayRequestResponse> bpCumulativeDynamicPayRequestAsync(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl) {
            PrivateTraining.Shaparak.bpCumulativeDynamicPayRequest inValue = new PrivateTraining.Shaparak.bpCumulativeDynamicPayRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpCumulativeDynamicPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            return ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpCumulativeDynamicPayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateTraining.Shaparak.bpPayRequestResponse PrivateTraining.Shaparak.IPaymentGateway.bpPayRequest(PrivateTraining.Shaparak.bpPayRequest request) {
            return base.Channel.bpPayRequest(request);
        }
        
        public string bpPayRequest(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            PrivateTraining.Shaparak.bpPayRequest inValue = new PrivateTraining.Shaparak.bpPayRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            PrivateTraining.Shaparak.bpPayRequestResponse retVal = ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpPayRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpPayRequestResponse> PrivateTraining.Shaparak.IPaymentGateway.bpPayRequestAsync(PrivateTraining.Shaparak.bpPayRequest request) {
            return base.Channel.bpPayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpPayRequestResponse> bpPayRequestAsync(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            PrivateTraining.Shaparak.bpPayRequest inValue = new PrivateTraining.Shaparak.bpPayRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpPayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            return ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpPayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateTraining.Shaparak.bpSaleReferenceIdRequestResponse PrivateTraining.Shaparak.IPaymentGateway.bpSaleReferenceIdRequest(PrivateTraining.Shaparak.bpSaleReferenceIdRequest request) {
            return base.Channel.bpSaleReferenceIdRequest(request);
        }
        
        public string bpSaleReferenceIdRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId) {
            PrivateTraining.Shaparak.bpSaleReferenceIdRequest inValue = new PrivateTraining.Shaparak.bpSaleReferenceIdRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpSaleReferenceIdRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            PrivateTraining.Shaparak.bpSaleReferenceIdRequestResponse retVal = ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpSaleReferenceIdRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpSaleReferenceIdRequestResponse> PrivateTraining.Shaparak.IPaymentGateway.bpSaleReferenceIdRequestAsync(PrivateTraining.Shaparak.bpSaleReferenceIdRequest request) {
            return base.Channel.bpSaleReferenceIdRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpSaleReferenceIdRequestResponse> bpSaleReferenceIdRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId) {
            PrivateTraining.Shaparak.bpSaleReferenceIdRequest inValue = new PrivateTraining.Shaparak.bpSaleReferenceIdRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpSaleReferenceIdRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            return ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpSaleReferenceIdRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateTraining.Shaparak.bpChargePayRequestResponse PrivateTraining.Shaparak.IPaymentGateway.bpChargePayRequest(PrivateTraining.Shaparak.bpChargePayRequest request) {
            return base.Channel.bpChargePayRequest(request);
        }
        
        public string bpChargePayRequest(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            PrivateTraining.Shaparak.bpChargePayRequest inValue = new PrivateTraining.Shaparak.bpChargePayRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpChargePayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            PrivateTraining.Shaparak.bpChargePayRequestResponse retVal = ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpChargePayRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpChargePayRequestResponse> PrivateTraining.Shaparak.IPaymentGateway.bpChargePayRequestAsync(PrivateTraining.Shaparak.bpChargePayRequest request) {
            return base.Channel.bpChargePayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpChargePayRequestResponse> bpChargePayRequestAsync(long terminalId, string userName, string userPassword, long orderId, long amount, string localDate, string localTime, string additionalData, string callBackUrl, long payerId) {
            PrivateTraining.Shaparak.bpChargePayRequest inValue = new PrivateTraining.Shaparak.bpChargePayRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpChargePayRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.amount = amount;
            inValue.Body.localDate = localDate;
            inValue.Body.localTime = localTime;
            inValue.Body.additionalData = additionalData;
            inValue.Body.callBackUrl = callBackUrl;
            inValue.Body.payerId = payerId;
            return ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpChargePayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateTraining.Shaparak.bpInquiryRequestResponse PrivateTraining.Shaparak.IPaymentGateway.bpInquiryRequest(PrivateTraining.Shaparak.bpInquiryRequest request) {
            return base.Channel.bpInquiryRequest(request);
        }
        
        public string bpInquiryRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            PrivateTraining.Shaparak.bpInquiryRequest inValue = new PrivateTraining.Shaparak.bpInquiryRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpInquiryRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            PrivateTraining.Shaparak.bpInquiryRequestResponse retVal = ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpInquiryRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpInquiryRequestResponse> PrivateTraining.Shaparak.IPaymentGateway.bpInquiryRequestAsync(PrivateTraining.Shaparak.bpInquiryRequest request) {
            return base.Channel.bpInquiryRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpInquiryRequestResponse> bpInquiryRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId) {
            PrivateTraining.Shaparak.bpInquiryRequest inValue = new PrivateTraining.Shaparak.bpInquiryRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpInquiryRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            return ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpInquiryRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PrivateTraining.Shaparak.bpRefundRequestResponse PrivateTraining.Shaparak.IPaymentGateway.bpRefundRequest(PrivateTraining.Shaparak.bpRefundRequest request) {
            return base.Channel.bpRefundRequest(request);
        }
        
        public string bpRefundRequest(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId, long refundAmount) {
            PrivateTraining.Shaparak.bpRefundRequest inValue = new PrivateTraining.Shaparak.bpRefundRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpRefundRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            inValue.Body.refundAmount = refundAmount;
            PrivateTraining.Shaparak.bpRefundRequestResponse retVal = ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpRefundRequest(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpRefundRequestResponse> PrivateTraining.Shaparak.IPaymentGateway.bpRefundRequestAsync(PrivateTraining.Shaparak.bpRefundRequest request) {
            return base.Channel.bpRefundRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<PrivateTraining.Shaparak.bpRefundRequestResponse> bpRefundRequestAsync(long terminalId, string userName, string userPassword, long orderId, long saleOrderId, long saleReferenceId, long refundAmount) {
            PrivateTraining.Shaparak.bpRefundRequest inValue = new PrivateTraining.Shaparak.bpRefundRequest();
            inValue.Body = new PrivateTraining.Shaparak.bpRefundRequestBody();
            inValue.Body.terminalId = terminalId;
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.orderId = orderId;
            inValue.Body.saleOrderId = saleOrderId;
            inValue.Body.saleReferenceId = saleReferenceId;
            inValue.Body.refundAmount = refundAmount;
            return ((PrivateTraining.Shaparak.IPaymentGateway)(this)).bpRefundRequestAsync(inValue);
        }
    }
}
