// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace PrivateTraining.Areas.Framework.Controllers
{
    public partial class PaymentController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PaymentController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.JsonResult> LoadPageMellat()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LoadPageMellat);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.JsonResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CallBackUrlMellats()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CallBackUrlMellats);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.JsonResult> LoadPageZarinPal()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LoadPageZarinPal);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.JsonResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SendZarinPal()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendZarinPal);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PaymentController Actions { get { return MVC.Framework.Payment; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Framework";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Payment";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Payment";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string ShowPageOfOnlinePayment = "ShowPageOfOnlinePayment";
            public readonly string ListBanks = "ListBanks";
            public readonly string LoadPageMellat = "LoadPageMellat";
            public readonly string CallBackUrlMellats = "CallBackUrlMellats";
            public readonly string CallBackUrlMellat = "CallBackUrlMellat";
            public readonly string LoadPageZarinPal = "LoadPageZarinPal";
            public readonly string SendZarinPal = "SendZarinPal";
            public readonly string CallBackUrlZarinPalCustomer = "CallBackUrlZarinPalCustomer";
            public readonly string CallBackUrlZarinPal = "CallBackUrlZarinPal";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string ShowPageOfOnlinePayment = "ShowPageOfOnlinePayment";
            public const string ListBanks = "ListBanks";
            public const string LoadPageMellat = "LoadPageMellat";
            public const string CallBackUrlMellats = "CallBackUrlMellats";
            public const string CallBackUrlMellat = "CallBackUrlMellat";
            public const string LoadPageZarinPal = "LoadPageZarinPal";
            public const string SendZarinPal = "SendZarinPal";
            public const string CallBackUrlZarinPalCustomer = "CallBackUrlZarinPalCustomer";
            public const string CallBackUrlZarinPal = "CallBackUrlZarinPal";
        }


        static readonly ActionParamsClass_ShowPageOfOnlinePayment s_params_ShowPageOfOnlinePayment = new ActionParamsClass_ShowPageOfOnlinePayment();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ShowPageOfOnlinePayment ShowPageOfOnlinePaymentParams { get { return s_params_ShowPageOfOnlinePayment; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ShowPageOfOnlinePayment
        {
            public readonly string OrderId = "OrderId";
            public readonly string TypeOrder = "TypeOrder";
            public readonly string OrderPrice = "OrderPrice";
            public readonly string CountOfOrder = "CountOfOrder";
        }
        static readonly ActionParamsClass_LoadPageMellat s_params_LoadPageMellat = new ActionParamsClass_LoadPageMellat();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoadPageMellat LoadPageMellatParams { get { return s_params_LoadPageMellat; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoadPageMellat
        {
            public readonly string DebtId = "DebtId";
            public readonly string Price = "Price";
            public readonly string OrderId = "OrderId";
            public readonly string TransactionType = "TransactionType";
            public readonly string CurrentUserId = "CurrentUserId";
        }
        static readonly ActionParamsClass_CallBackUrlMellats s_params_CallBackUrlMellats = new ActionParamsClass_CallBackUrlMellats();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CallBackUrlMellats CallBackUrlMellatsParams { get { return s_params_CallBackUrlMellats; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CallBackUrlMellats
        {
            public readonly string Price = "Price";
            public readonly string OrderId = "OrderId";
        }
        static readonly ActionParamsClass_LoadPageZarinPal s_params_LoadPageZarinPal = new ActionParamsClass_LoadPageZarinPal();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LoadPageZarinPal LoadPageZarinPalParams { get { return s_params_LoadPageZarinPal; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LoadPageZarinPal
        {
            public readonly string DebtId = "DebtId";
            public readonly string Price = "Price";
            public readonly string Type = "Type";
            public readonly string CurrentUserId = "CurrentUserId";
        }
        static readonly ActionParamsClass_SendZarinPal s_params_SendZarinPal = new ActionParamsClass_SendZarinPal();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SendZarinPal SendZarinPalParams { get { return s_params_SendZarinPal; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SendZarinPal
        {
            public readonly string Price = "Price";
            public readonly string PaymentIds = "PaymentIds";
            public readonly string CurrentUserId = "CurrentUserId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CallBackUrlMellat = "CallBackUrlMellat";
                public readonly string CallBackUrlMellats = "CallBackUrlMellats";
                public readonly string CallBackUrlZarinPal = "CallBackUrlZarinPal";
                public readonly string CallBackUrlZarinPalCustomer = "CallBackUrlZarinPalCustomer";
                public readonly string SendZarinPal = "SendZarinPal";
                public readonly string ShowPageOfOnlinePayment = "ShowPageOfOnlinePayment";
                public readonly string test = "test";
            }
            public readonly string CallBackUrlMellat = "~/Areas/Framework/Views/Payment/CallBackUrlMellat.cshtml";
            public readonly string CallBackUrlMellats = "~/Areas/Framework/Views/Payment/CallBackUrlMellats.cshtml";
            public readonly string CallBackUrlZarinPal = "~/Areas/Framework/Views/Payment/CallBackUrlZarinPal.cshtml";
            public readonly string CallBackUrlZarinPalCustomer = "~/Areas/Framework/Views/Payment/CallBackUrlZarinPalCustomer.cshtml";
            public readonly string SendZarinPal = "~/Areas/Framework/Views/Payment/SendZarinPal.cshtml";
            public readonly string ShowPageOfOnlinePayment = "~/Areas/Framework/Views/Payment/ShowPageOfOnlinePayment.cshtml";
            public readonly string test = "~/Areas/Framework/Views/Payment/test.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PaymentController : PrivateTraining.Areas.Framework.Controllers.PaymentController
    {
        public T4MVC_PaymentController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ShowPageOfOnlinePaymentOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int OrderId, int TypeOrder, string OrderPrice, byte CountOfOrder);

        [NonAction]
        public override System.Web.Mvc.ActionResult ShowPageOfOnlinePayment(int OrderId, int TypeOrder, string OrderPrice, byte CountOfOrder)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ShowPageOfOnlinePayment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "OrderId", OrderId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "TypeOrder", TypeOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "OrderPrice", OrderPrice);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "CountOfOrder", CountOfOrder);
            ShowPageOfOnlinePaymentOverride(callInfo, OrderId, TypeOrder, OrderPrice, CountOfOrder);
            return callInfo;
        }

        [NonAction]
        partial void ListBanksOverride(T4MVC_System_Web_Mvc_JsonResult callInfo);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.JsonResult> ListBanks()
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ListBanks);
            ListBanksOverride(callInfo);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.JsonResult);
        }

        [NonAction]
        partial void LoadPageMellatOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string[] DebtId, double Price, int OrderId, byte TransactionType, int CurrentUserId);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.JsonResult> LoadPageMellat(string[] DebtId, double Price, int OrderId, byte TransactionType, int CurrentUserId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LoadPageMellat);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "DebtId", DebtId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Price", Price);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "OrderId", OrderId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "TransactionType", TransactionType);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "CurrentUserId", CurrentUserId);
            LoadPageMellatOverride(callInfo, DebtId, Price, OrderId, TransactionType, CurrentUserId);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.JsonResult);
        }

        [NonAction]
        partial void CallBackUrlMellatsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Price, int OrderId);

        [NonAction]
        public override System.Web.Mvc.ActionResult CallBackUrlMellats(int Price, int OrderId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CallBackUrlMellats);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Price", Price);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "OrderId", OrderId);
            CallBackUrlMellatsOverride(callInfo, Price, OrderId);
            return callInfo;
        }

        [NonAction]
        partial void CallBackUrlMellatOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CallBackUrlMellat()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CallBackUrlMellat);
            CallBackUrlMellatOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LoadPageZarinPalOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string[] DebtId, int Price, byte Type, int CurrentUserId);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.JsonResult> LoadPageZarinPal(string[] DebtId, int Price, byte Type, int CurrentUserId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.LoadPageZarinPal);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "DebtId", DebtId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Price", Price);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Type", Type);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "CurrentUserId", CurrentUserId);
            LoadPageZarinPalOverride(callInfo, DebtId, Price, Type, CurrentUserId);
            return System.Threading.Tasks.Task.FromResult(callInfo as System.Web.Mvc.JsonResult);
        }

        [NonAction]
        partial void SendZarinPalOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int Price, int PaymentIds, int CurrentUserId);

        [NonAction]
        public override System.Web.Mvc.ActionResult SendZarinPal(int Price, int PaymentIds, int CurrentUserId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SendZarinPal);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Price", Price);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "PaymentIds", PaymentIds);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "CurrentUserId", CurrentUserId);
            SendZarinPalOverride(callInfo, Price, PaymentIds, CurrentUserId);
            return callInfo;
        }

        [NonAction]
        partial void CallBackUrlZarinPalCustomerOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CallBackUrlZarinPalCustomer()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CallBackUrlZarinPalCustomer);
            CallBackUrlZarinPalCustomerOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CallBackUrlZarinPalOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult CallBackUrlZarinPal()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CallBackUrlZarinPal);
            CallBackUrlZarinPalOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
